replicaCount: 2
image:
  # This sets the container image more information can be found here: https://kubernetes.io/docs/concepts/containers/images/
  repository: vijaygodson/${{values.app_name}}
  pullPolicy: Always
  tag: ${{values.app_name}}-${{values.app_nenvv}}:latest'

  resources:
    requests:
      cpu: 60m
      memory: 60M